[2023-05-29T10:14:16.790+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T10:14:16.796+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T10:14:16.797+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-29T10:14:16.816+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-28 00:00:00+00:00
[2023-05-29T10:14:16.824+0000] {standard_task_runner.py:57} INFO - Started process 580 to run task
[2023-05-29T10:14:16.827+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-05-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp33yc_xro']
[2023-05-29T10:14:16.830+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask create_table
[2023-05-29T10:14:16.909+0000] {task_command.py:410} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [running]> on host 280eb86c6caa
[2023-05-29T10:14:16.985+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-28T00:00:00+00:00'
[2023-05-29T10:14:16.987+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        
[2023-05-29T10:14:17.281+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-05-29T10:14:17.285+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20230528T000000, start_date=20230529T101416, end_date=20230529T101417
[2023-05-29T10:14:17.293+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task create_table (The conn_id `postgres` isn't defined; 580)
[2023-05-29T10:14:17.328+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-29T10:14:17.348+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-29T12:25:58.149+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T12:25:58.155+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T12:25:58.156+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-29T12:25:58.163+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-28 00:00:00+00:00
[2023-05-29T12:25:58.167+0000] {standard_task_runner.py:57} INFO - Started process 2935 to run task
[2023-05-29T12:25:58.171+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-05-28T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpqhvhwk_o']
[2023-05-29T12:25:58.173+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_table
[2023-05-29T12:25:58.212+0000] {task_command.py:410} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-05-28T00:00:00+00:00 [running]> on host 280eb86c6caa
[2023-05-29T12:25:58.266+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-28T00:00:00+00:00'
[2023-05-29T12:25:58.267+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        
[2023-05-29T12:25:58.274+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-29T12:25:58.321+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-29T12:25:58.326+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-05-29T12:25:58.335+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230528T000000, start_date=20230529T122558, end_date=20230529T122558
[2023-05-29T12:25:58.386+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-05-29T12:25:58.408+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
