[2023-05-29T12:26:02.228+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.store_user scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T12:26:02.234+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.store_user scheduled__2023-05-28T00:00:00+00:00 [queued]>
[2023-05-29T12:26:02.234+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-05-29T12:26:02.242+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): store_user> on 2023-05-28 00:00:00+00:00
[2023-05-29T12:26:02.246+0000] {standard_task_runner.py:57} INFO - Started process 2947 to run task
[2023-05-29T12:26:02.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2023-05-28T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpb9_qeopz']
[2023-05-29T12:26:02.251+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask store_user
[2023-05-29T12:26:02.290+0000] {task_command.py:410} INFO - Running <TaskInstance: user_processing.store_user scheduled__2023-05-28T00:00:00+00:00 [running]> on host 280eb86c6caa
[2023-05-29T12:26:02.343+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='store_user' AIRFLOW_CTX_EXECUTION_DATE='2023-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-28T00:00:00+00:00'
[2023-05-29T12:26:02.344+0000] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-05-29T12:26:02.351+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-29T12:26:02.357+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-29T12:26:02.366+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20230528T000000, start_date=20230529T122602, end_date=20230529T122602
[2023-05-29T12:26:02.381+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-05-29T12:26:02.394+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
